<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration [
 <!ELEMENT configuration (property+)>
 <!ELEMENT property (name,value,description*)>
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT value (#PCDATA) >
 <!ELEMENT description (#PCDATA)>
]>
<configuration>
	<property>
		<name>source.driver</name>
		<value>oracle.jdbc.OracleDriver</value>
	</property>
	<property>
		<name>source.url</name>
		<value>jdbc:oracle:thin:@10.150.0.231:1521:gddw1</value>
		<description>导入源表的数据库url地址</description>
	</property>
	<property>
		<name>source.username</name>
		<value>dw_pmis</value>
	</property>
	<property>
		<name>source.password</name>
		<value>oracle_dwpmis</value>
	</property>
	<property>
		<name>source.owner</name>
		<value>dw_pmis</value>
	</property>
	<property>
		<name>source.dbname</name>
		<value>YXXT</value>
	</property>
	<property>
		<name>target.dbname</name>
		<value>CJCK</value>
	</property>
	<property>
		<name>target.prefix</name>
		<value>T_</value>
	</property>
	<property>
		<name>map.prefix</name>
		<value>M_</value>
	</property>
	<property>
		<name>map.postfix</name>
		<value>_INC</value>
	</property>
	<property>
		<name>qualifier.prefix</name>
		<value>SQ_</value>
	</property>
	<property>
		<name>infa.folder</name>
		<value>TEST</value>
	</property>
	<property>
		<name>xml.output</name>
		<value>FILE.xml</value>
	</property>
	<property>
		<name>xml.output.mappings</name>
		<value>3</value>
		<description>每个文件中mapping数量</description>
	</property>
	<property>
		<name>tables</name>
		<value>d:\\tables.txt</value>
		<description>需要生成xml文件的表清单文件</description>
	</property>
	<property>
		<name>tables.notable</name>
		<value>no_table.txt</value>
	</property>
	<property>
		<name>tables.noprimarykey</name>
		<value>no_primarykey.txt</value>
	</property>
	<property>
		<name>workflow.prefix</name>
		<value>WF_</value>
	</property>
	<property>
		<name> service.name</name>
		<value>infa_is</value>
	</property>
	<property>
		<name> server.domainname</name>
		<value>GDDW_GRID_DM</value>
	</property>
	<property>
		<name> session.prefix</name>
		<value>S_</value>
	</property>
	<property>
		<name> workflow.paramter.filename</name>
		<value>/home/infa/AAA.txt</value>
	</property>
	<property>
		<name>mapping.variable</name>
		<value>$$unit_id,string,10</value>
	</property>	
	<property>
		<name>sql.filter</name>
		<value>unit_id=$$unit_id</value>
	</property>	
</configuration>